---

- name: Oration Staging Build
  hosts: all
  tasks:
    # This is a little expensive, but it makes sure you don't fail to complie (provided your build isn't broken)
    # Fist, the musl builder image is pulled (if there's a new version), then we update rust to the latest nightly
    # inside th container, and finally build the static oration file.
    - name: Backend | Build production executable
      shell: |
        docker pull ekidd/rust-musl-builder:nightly
        alias rust-musl-builder='docker run --rm -t -v {{playbook_dir}}/..:/home/rust/src ekidd/rust-musl-builder:nightly'
        rust-musl-builder rustup update && cargo build --release

    - name: Backend | Check for deployment directory
      file:
        path: deploy
        state: directory

    - name: Backend | Ready configuration file
      copy:
        src: ../oration.yaml
        dest: deploy/oration.yaml

    - name: Backend | Setting localhost as blog entrypoint
      replace:
        path: deploy/oration.yaml
        regexp: '^(host:\s+).*'
        replace: '\1http://localhost/'

    - name: Backend | Ready executable file
      copy:
        src: ../target/x86_64-unknown-linux-musl/release/oration
        dest: deploy/oration
        mode: u+rwx,g-wx,o-rwx

    - name: Database | Environment file
      copy:
        src: ../.env
        dest: deploy/.env

    - name: Database | Ready database
      copy:
        src: ../oration.db
        dest: deploy/oration.db

    - name: Frontend | Build Elm app
      command: npm run deploy
      args:
        chdir: ../app

    - name: Frontend | Finding map files in public area
      find:
        paths: ../public
        patterns: "*.map"
        recurse: yes
      register: map_files

    - name: Frontend | Removing map files from public area
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ map_files.files }}"
