language: rust
cache: cargo
sudo: true
dist: trusty
os: linux
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_install:
  - sudo apt-get update
addons:
  apt:
    packages:
      - sqlite3
before_script:
  - ( ( cargo install clippy && export CLIPPY=true ) || export CLIPPY=false );
  - cargo install diesel_cli --no-default-features --features sqlite
  - export PATH=$PATH:~/.cargo/bin
  - echo "DATABASE_URL=oration.db" > .env
  - diesel migration run
script:
  - cargo build
  - cargo test
  - |
      if [[ $CLIPPY = "true" ]]; then
        cargo build --features="clippy"
      fi
after_success:
  # Upload docs
  - |
      if [[ "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
        cargo rustdoc -- --no-defaults --passes collapse-docs --passes unindent-comments --passes strip-priv-imports &&
        cp logo/logo_wbl.svg target/doc/ &&
        echo "<meta http-equiv=refresh content=0;url=oration/index.html>" > target/doc/index.html &&
        git clone https://github.com/davisp/ghp-import.git &&
        ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/doc &&
        echo "Uploaded documentation"
      fi

