[package]
name = "oration"
version = "0.1.0"
authors = ["Tim DuBois <tim@neophilus.net>"]

[dependencies]
rocket = "0.2.9"
rocket_codegen = "0.2.9"
rusqlite = "0.12"

[dev-dependencies]
rocket = { version = "0.2.9", features = ["testing"] }
