[package]
name = "oration"
version = "0.1.0"
authors = ["Tim DuBois <tim@neophilus.net>"]

[dependencies]
rocket = "0.3"
rocket_codegen = "0.3"
diesel = { version = "0.14", features = ["sqlite"] }
diesel_codegen = { version = "0.14", features = ["sqlite"] }
r2d2-diesel = "0.14"
r2d2 = "0.7"
